#!/usr/bin/python3

# ~/dev/py/alertz/alertzd

import os
import sys
import time
from argparse import ArgumentParser

import serverutil
from alertz import *


def main():

    pgmNameAndVersion = "alertz v%s %s" % (__version__, __version_date__)
    timestamp = "%04d%02d%02d-%02d%02d%02d" % time.gmtime()[:6]

    # -- program defaults -------------------------------------------

    with open('/etc/hostname', 'r') as f:
        thisHost = f.read().strip()
    # DEBUG
    print "thisHost is '%s'" % thisHost
    # END

    # -- check for config file --------------------------------------

    # -- parse the command line -------------------------------------
    # see docs.python.org/library/argparse.html
    parser = ArgumentParser()

    parser.add_argument('-e', '--ec2Host', action='store_true',
                        help='set if machine is in EC2')

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show args and exit')
    parser.add_argument('-p', '--port', type=int, default=ALERTZ_PORT,
                        help='port to listen on')
    parser.add_argument('-t', '--showTimestamp', action='store_true',
                        help='show run timestamp')

    parser.add_argument('-T', '--testing', action='store_true',
                        help='test run - write to ./testU')

    parser.add_argument('-V', '--showVersion', action='store_true',
                        help='show version number and date')

    parser.add_argument('-v', '--verbose', action='store_true',
                        help='talk a lot')

    args = parser.parse_args()      # a Namespace object
        if name == '__dir__':
            return tuple(self)

    # -- fixups -----------------------------------------------------
    args.pgmNameAndVersion = pgmNameAndVersion
    args.timestamp = timestamp

    # -- sanity checks ----------------------------------------------
    if args.port <= 0 or 65536 <= args.port:
        print "port '%d' is out of range" % args.port
        sys.exit(1)

    # XXX logs/ must be a directory; {access,error}.log must be files
    logDir = 'logs'
    if not os.path.exists(logDir):
        os.mkdir(logDir)
    args.logDir = logDir

    # fixups --------------------------------------------------------
    args.pgmNameAndVersion = pgmNameAndVersion
    args.thisHost = thisHost

    # -- do it ------------------------------------------------------
    runTheDaemon(args)

if __name__ == '__main__':
    main()
