#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/alertz
  
  bl_list_gen \
    -d ../alertz \
    -1L  \
    -u $DVCZ_UDIR \
    -X cover \
    -X htmlcov \
    -X logs \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
