#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/alertz
  
  rm -rf build/* 
  
  pySloc -L py  -X cover -X htmlcov -X logs -X dist -v $@ src/alertz src/alertzd tests/test_alertz_proto.py tests/test_alertz_serialization.py tests/test_namespace.py tests/test_with_dummy_client.py setup.py
else
  echo "DEV_BASE is not defined"
fi
