#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/alertz
  
  rm -rf build/* 
  
  runpysloc -L py alertzd  -X cover -X htmlcov -X logs -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
