[meta]
version = "0.1.0"

[project]
name = "alertz"
package = "alertz"
relpath = "py/alertz"
main_lang = "py"
version = "0.2.20"
version_date = "2018-03-11"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2012-2017"
description = "alerts system for a cluster of computers"
dev_status = "pre_alpha"
license = "mit"
state = "shared"
url = "https://jddixon.github.io/alertz"

[py]
packages = [ "alertz",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = [ "src/alertzd",]
ext_modules = []
distshare = [ "fieldz", "optionz", "rnglib", "wireops", "xlattice_py",]
env_vars = []
requirements = [ "alertz_proto_spec", "setuptools",]
test_requirements = []
